# Generated by Django 4.1.5 on 2023-10-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='A_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname1', models.CharField(max_length=20)),
                ('passw1', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='details',
            name='uname',
            field=models.CharField(max_length=20),
        ),
    ]
